Repository ossf/gemara, pull requests merged in 2025-09, with the labels that each got.

#115 chore: Update CODEOWNERS to assign @ossf/gemara
  .github/CODEOWNERS
Labels: maintenance

#118 chore: rm last reference to sci
  security-insights.yml
Labels: maintenance

#121 fix: allow unknown fields in catalogs
  layer2/loaders.go
  layer2/loaders_test.go
  layer2/test-data/bad.yaml
Labels: fix

#123 feat: adds layer3 loader and layer2 loader support for json
  .github/workflows/ci.yml
  Makefile
  internal/loaders/loaders.go
  internal/loaders/loaders_test.go
  layer2/loaders.go
  layer2/loaders_test.go
  layer2/test-data/bad.json
  layer2/test-data/good-ccc.json
  layer3/loaders.go
  layer3/loaders_test.go
  layer3/test-data/bad.json
  layer3/test-data/bad.yaml
  layer3/test-data/good-policy.yaml
  layer3/test-data/good-security-policy.yml
  layer3/test-data/good.json
  layer3/test-data/unsupported.txt
Labels: feature

#131 fix: Load Imported Capabilities, Threats, and Controls
  layer2/loaders.go
Labels: fix

#137 refactor: updates internal OSCAL version const to go-oscal
  internal/oscal/utils.go
  layer1/oscal_generator.go
  layer2/oscal_generator.go
Labels: automation

#141 fix: update dependabot labels
  .github/dependabot.yaml
  .github/release-drafter.yml
Labels: fix

#117 feat!: adds `EvaluationPlan` to layer 4 schema
  layer4/assessment_log.go
  layer4/assessment_log_test.go
  layer4/control_evaluation.go
  layer4/control_evaluation_test.go
  layer4/evaluation_plan.go
  layer4/test-data.go
  layer4/test-data/pvtr-baseline-scan.yaml
  schemas/layer-4.cue
Labels: feature

#138 feat: transform recommendation to guidance in layer2 OSCAL generation
  layer2/oscal_generator.go
  layer2/test-data/good-osps.yml
Labels: feature

#147 docs: updates project communication spaces
  README.md
Labels: documentation

#150 fix: Reorganized layer4 top level context
  layer4/evaluation_log.go
  layer4/evaluation_plan.go
  layer4/to_sarif_test.go
  schemas/layer-4.cue
Labels: fix
