Repository ossf/gemara, pull requests merged in 2025-08, with the labels that each got.

#75 chore: Rename SCI -> Gemara as part of OpenSSF donation
  .github/ISSUE_TEMPLATES/bug_report.yml
  .github/ISSUE_TEMPLATES/config.yml
  .github/workflows/ci.yml
  CONTRIBUTING.md
  README.md
  go.mod
  security-insights.yml
Labels: maintenance

#79 chore: update Makefile with layer 3 liniting and cuegen
  Makefile
Labels: maintenance

#81 chore: Updated godoc lines for layer 2
  layer2/loaders.go
Labels: maintenance

#80 chore: Minor documentation updates
  README.md
Labels: maintenance

#98 chore(deps): Bump ospo-reusable-workflows/auto-labeler to 23b65d1
  .github/workflows/auto-labeler.yml
Labels: maintenance

#104 docs: improve ToOSCAL function parameter documentation
  layer2/oscal_generator.go
Labels: documentation

#106 fix: Simplify ToOSCAL function to use internal IDs/version, generate UUID internally
  layer2/oscal_generator.go
  layer2/oscal_generator_test.go
Labels: fix

#107 fix: more revanite-io to ossf renames
  .github/ISSUE_TEMPLATES/config.yml
  CONTRIBUTING.md
  README.md
  security-insights.yml
Labels: fix

#105 chore: add cue fmt usage and checks in CI
  .github/workflows/ci.yml
  CONTRIBUTING.md
  Makefile
  schemas/layer-1.cue
  schemas/layer-2.cue
  schemas/layer-3.cue
  schemas/layer-4.cue
Labels: maintenance

#109 fix: Move control remediation guide to assessment recommendation
  layer4/assessment.go
  layer4/control_evaluation.go
  layer4/test-data/pvtr-baseline-scan.yaml
  schemas/layer-4.cue
Labels: fix

#111 chore(ci): upgrade golangci-lint to v2.4.0
  .github/workflows/lint.yml
Labels: maintenance
